
# Plotly and Cufflinks

Plotly is a library that allows you to create interactive plots that you can use in dashboards or websites (you can save them as html files or static images).

In [1]:
import pandas as pd
import numpy as np
%matplotlib inline

In [2]:
from plotly import __version__
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

print(__version__) # requires version >= 1.9.0

6.8.0

In [3]:
import cufflinks as cf

In [4]:
# For Notebooks
init_notebook_mode(connected=True)

In [5]:
# For offline use
cf.go_offline()

### Fake Data

In [6]:
df = pd.DataFrame(np.random.randn(100,4),columns='A B C D'.split())

In [7]:
df.head()

          A         B         C         D
0 -1.016176  0.406488  1.089398 -1.214799
1 -0.070926  0.800685 -0.741013  1.497894
2  0.958245 -1.538543  1.098858  0.207671
3 -0.654216 -0.810578 -1.321927  0.520664
4 -0.157600  1.341582  0.020438  1.294379

In [8]:
df2 = pd.DataFrame({'Category':['A','B','C'],'Values':[32,43,50]})

In [9]:
df2.head()

  Category  Values
0        A      32
1        B      43
2        C      50

## Using Cufflinks and iplot()

* scatter
* bar
* box
* spread
* ratio
* heatmap
* surface
* histogram
* bubble

## Scatter

In [12]:
# df.iplot(kind='scatter',x='A',y='B',mode='markers',size=10)
# plt.show()

import plotly.express as px

# Create the interactive scatter plot and pass the marker size directly
fig = px.scatter(df, x="A", y="B", size_max=10)

# If you want ALL markers to be a fixed size of 10 explicitly:
fig.update_traces(marker=dict(size=10))

# Display the interactive Plotly graph
fig.show()

## Bar Plots

In [ ]:
df2.iplot(kind='bar',x='Category',y='Values')

In [ ]:
df.count().iplot(kind='bar')

## Boxplots

In [ ]:
df.iplot(kind='box')

## 3d Surface

In [ ]:
df3 = pd.DataFrame({'x':[1,2,3,4,5],'y':[10,20,30,20,10],'z':[5,4,3,2,1]})
df3.iplot(kind='surface',colorscale='rdylbu')

## Spread

In [ ]:
df[['A','B']].iplot(kind='spread')

## histogram

In [ ]:
df['A'].iplot(kind='hist',bins=25)

In [ ]:
df.iplot(kind='bubble',x='A',y='B',size='C')

## scatter_matrix()

Similar to sns.pairplot()

In [ ]:
df.scatter_matrix()